@base_url=http://localhost:8080

POST {{base_url}}/todos
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NzgwNzkwMDh9.XhE52MCIzsyhgcNvWIXrSZg48mRbLomUxYnzF6p5kqA

{
    "text": "test 1"
}